### PR TITLE
Src utils

### PR DESCRIPTION
**Pull request by hokin2023**
added components/src/utils for mutations and queries. Added schemas and models

### CODE REVIEW

**Review by dustinii — COMMENTED** [review]
please make so only email and password are required for login. rides should have an origin, destination, time for departure, and price

**Comment by sammyrey6** [comment]
schemas needs to be lowercased on your const { Schema, model } = require('mongoose'); lines

**Comment by hokin2023** [comment]
> schemas needs to be lowercased on your const { Schema, model } = require('mongoose'); lines

I think It has to be uppercase since it's not an arbitrary. I used uppercase Schema on my homework and mini-project, and they both worked.

**Review by sammyrey6 — APPROVED** [review]
Mb looks good  !

**Pull request merged**
